name: Publish Docker images to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: edoc
      MYSQL_USER: root
      MYSQL_PASSWORD: root

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: aadish1206
          password: "Aadish12@"

      - name: Build and Push php-env Docker Image
        working-directory: ./php-env
        run: |
          docker build -t aadish1206/php-env .
          docker push aadish1206/php-env

      - name: Build and Push mysql_db Docker Image
        working-directory: ./mysql_db
        run: |
          docker build -t aadish1206/mysql_db .
          docker push aadish1206/mysql_db

      - name: Build and Push phpmyadmin Docker Image
        working-directory: ./phpmyadmin
        run: |
          docker build -t aadish1206/phpmyadmin .
          docker push aadish1206/phpmyadmin
