name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: aadish1206
        password: Aadish12@

    - name: Build and Push PHP-Env image
      run: |
        docker-compose -f =docker-compose.yaml build php-env
        docker-compose -f =docker-compose.yaml push php-env

    - name: Build and Push MySQL-DB image
      run: |
        docker-compose -f docker-compose.yaml build mysql_db
        docker-compose -f docker-compose.yaml push mysql_db

    - name: Build and Push PHPMyAdmin image
      run: |
        docker-compose -f docker-compose.yaml build phpmyadmin
        docker-compose docker-compose.yaml push phpmyadmin

    - name: Run Docker Compose
      run: |
        docker-compose -f docker-compose.yaml up --build -d

    - name: Wait for services to start
      run: sleep 10  # Adjust the wait time as needed
      
    - name: Stop Docker Compose
      run: |
        docker-compose -f docker-compose.yaml down



docker-compose.yaml
