name: Docker Build and Push

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: aadish1206
        password: "Aadish12@"

    - name: Build and Push php-env image
      run: |
        docker build -t aadish1206/php-env:latest -f docker-compose.yaml/php-env .
        docker push aadish1206/php-env:latest

    - name: Build and Push mysql_db image
      run: |
        docker build -t aadish1206/mysql_db:latest -f docker-compose.yaml/mysql_db .
        docker push aadish1206/mysql_db:latest

    - name: Build and Push phpmyadmin image
      run: |
        docker build -t aadish1206/phpmyadmin:latest -f docker-compose.yaml/phpmyadmin .
        docker push aadish1206/phpmyadmin:latest
