name: Docker Build and Publish

on:
  push:
    branches:
      - master  # Change this to your main branch name

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with: 
        username: aadish1206
        password: "Aadish12@"

    - name: Build and Push Docker Images
      run: |
        services=("php-env" "mysql_db" "phpmyadmin")
        for service in "${services[@]}"; do
          docker-compose build $service
          docker-compose push $service
        done

    - name: Run Docker Compose
      run: docker-compose up --build -d

    - name: Wait for services to start
      run: sleep 10  # Adjust the wait time as needed
      
    - name: Stop Docker Compose
      run: docker-compose down
